course = 'Python for Beginners'
print(course.upper())
print('############################')
print(course.lower())
print('############################')
print(course.find('Be'))
print('############################')
print(course.replace('Py', 'Ay'))
print('############################')
print('Python' in course)
print('############################')
print('python' in course)
print('############################')
print(course.title())