pipeline {
    agent any
    environment{
        DOCKERHUB_CREDS = credentials('dockerhub')
    }
    stages {
        stage('checkout') {
            steps {
                git branch: 'pushdockerimage', url: 'https://github.com/adikal49/lab.git' 
                sh 'ls *'
            }
        }
        stage('Build Image') {
            options {
                timeout(time: 5, unit: 'MINUTES') 
            }
	    steps {
                //sh 'docker build -t adicop49/jenkinstest ./pushdockerimage/' (this will use the tag latest)
		sh 'docker build -t adicop49/jenkinstest:$BUILD_NUMBER ./pushdockerimage/'
            }
        }
        stage('Docker Login') {
            options {
                timeout(time: 5, unit: 'MINUTES') 
            }
	    steps {
                //sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW' (this will leave the password visible)
                sh 'echo $DOCKERHUB_CREDS_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin'                
                }
            }
        stage('Docker Push') {
            options {
                timeout(time: 5, unit: 'MINUTES') 
            }
	    steps {
		//sh 'docker push adicop49/jenkinstest' (this will use the tag latest)    
                sh 'docker push adicop49/jenkinstest:$BUILD_NUMBER'
                }
            }
        }
    post {
		always {
			sh 'docker logout'
		}
	 }
    }

